# yaml-language-server: $schema=../cache/schemas/tasks.json
$schema: "../cache/schemas/tasks.json"

tasks:
  build:
    command: "go build -o @out(0)"
    inputs:
      - "@globs(sources)"
    outputs:
      - "bin/main"
  dev:
    command: "go run main.go"
    inputs:
      - "@globs(sources)"
  format:
    command: "go fmt ./..."
    inputs:
      - "@globs(sources)"
  lint:
    command: "staticcheck"
    inputs:
      - "@globs(sources)"
      - "staticcheck.conf"
  test:
    command: "go test ./..."
    inputs:
      - "@globs(sources)"
  typecheck:
    command: "go vet"
    inputs:
      - "@globs(sources)"
