# yaml-language-server: $schema=../cache/schemas/tasks.json
$schema: "../cache/schemas/tasks.json"

tasks:
  typecheck:
    command:
      - "tsc"
      - "--build"
      - "--pretty"
      - "--verbose"
    inputs:
      - "src/**/*"
      - "tests/**/*"
      - "types/**/*"
      - "tsconfig.json"
      - "tsconfig.*.json"
      - "/tsconfig.options.json"
