# yaml-language-server: $schema=../cache/schemas/tasks.json
$schema: "../cache/schemas/tasks.json"

extends: "https://raw.githubusercontent.com/moonrepo/moon-configs/master/javascript/vitest/tasks.yml"
